blank_issues_enabled: true
contact_links:
  - name: NekoSuneAPPSVRC Documentation
    url: https://github.com/NekoSuneProjects/NekoSuneAPPSVRC#readme
    about: Check the README before opening an issue.
